#!/usr/bin/env python3
"""
Send Report CLI - Send grade reports via email.

Usage:
    python -m cli.send_report                    # Send to all students
    python -m cli.send_report --student "JJ"     # Send for specific student
    python -m cli.send_report --test             # Send test email (no Canvas data)
    python -m cli.send_report --preview          # Preview in browser (no email)

Options:
    --student NAME    Send report for specific student only
    --test            Send a test email to verify Gmail setup
    --preview         Save HTML and open in browser instead of sending
    --to EMAIL        Override recipient email address
    --type TYPE       Report type: 'daily' or 'weekly' (default: daily)
    --no-chart        Skip chart generation
"""

import argparse
import os
import sys
import webbrowser
from typing import Optional, List

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import canvas_api
from config import get_config
from reports.report_builder import ReportBuilder
from google_services.gmail_service import GmailService


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Send Canvas grade reports via email",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument(
        "--student",
        type=str,
        help="Send report for specific student (by name)",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Send a test email to verify Gmail setup",
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Preview in browser instead of sending email",
    )
    parser.add_argument(
        "--to",
        type=str,
        help="Override recipient email address",
    )
    parser.add_argument(
        "--type",
        choices=["daily", "weekly"],
        default="daily",
        help="Report type (default: daily)",
    )
    parser.add_argument(
        "--no-chart",
        action="store_true",
        help="Skip chart generation",
    )

    return parser.parse_args()


def send_test_email(recipient: Optional[str] = None) -> bool:
    """Send a test email to verify Gmail setup."""
    print("Sending test email...")

    try:
        gmail = GmailService()
        sender = gmail.get_user_email()

        if not sender:
            print("Error: Could not authenticate with Gmail")
            return False

        to = recipient or sender
        print(f"From: {sender}")
        print(f"To: {to}")

        result = gmail.send_html_email(
            to=to,
            subject="Canvas Parent CLI - Test Email",
            html_body="""
            <html>
            <body style="font-family: Arial, sans-serif; padding: 20px;">
                <h1 style="color: #2c3e50;">Test Email</h1>
                <p>This is a test email from <strong>Canvas Parent CLI</strong>.</p>
                <p>If you received this, your Gmail integration is working correctly!</p>
                <hr>
                <p style="color: #7f8c8d; font-size: 12px;">
                    Generated by Canvas Parent CLI
                </p>
            </body>
            </html>
            """,
        )

        print(f"Email sent! Message ID: {result.get('id')}")
        return True

    except Exception as e:
        print(f"Error sending test email: {e}")
        return False


def preview_report(student_id: int, student_name: str, report_type: str, include_chart: bool) -> bool:
    """Generate and preview a report in the browser."""
    print(f"Generating {report_type} report for {student_name}...")

    try:
        config = get_config()
        builder = ReportBuilder()

        if report_type == "weekly":
            result = builder.build_weekly_report(
                student_id,
                student_name,
                include_chart=include_chart,
                grade_alert_threshold=config.email.grade_alert_threshold,
            )
        else:
            result = builder.build_daily_report(
                student_id,
                student_name,
                include_chart=include_chart,
                grade_alert_threshold=config.email.grade_alert_threshold,
            )

        # Save to temp file
        preview_path = f"/tmp/canvas_report_{student_name.replace(' ', '_')}.html"
        with open(preview_path, "w") as f:
            f.write(result["html"])

        print(f"Report saved to: {preview_path}")
        print(f"Subject: {result['subject']}")

        # Open in browser
        webbrowser.open(f"file://{preview_path}")

        builder.cleanup_temp_files()
        return True

    except Exception as e:
        print(f"Error generating preview: {e}")
        return False


def send_report(
    student_id: int,
    student_name: str,
    recipients: List[str],
    report_type: str,
    include_chart: bool,
) -> bool:
    """Generate and send a report for a student."""
    print(f"Generating {report_type} report for {student_name}...")

    try:
        config = get_config()
        builder = ReportBuilder()

        if report_type == "weekly":
            result = builder.build_weekly_report(
                student_id,
                student_name,
                include_chart=include_chart,
                grade_alert_threshold=config.email.grade_alert_threshold,
            )
        else:
            result = builder.build_daily_report(
                student_id,
                student_name,
                include_chart=include_chart,
                grade_alert_threshold=config.email.grade_alert_threshold,
            )

        print(f"Subject: {result['subject']}")
        print(f"Sending to: {', '.join(recipients)}")

        # Send email
        gmail = GmailService()
        send_result = gmail.send_html_email(
            to=recipients,
            subject=result["subject"],
            html_body=result["html"],
            embedded_images=result["images"],
        )

        print(f"Email sent! Message ID: {send_result.get('id')}")

        builder.cleanup_temp_files()
        return True

    except Exception as e:
        print(f"Error sending report: {e}")
        return False


def main():
    """Main entry point."""
    args = parse_args()

    print("Canvas Parent CLI - Send Report")
    print("=" * 50)

    # Handle test email
    if args.test:
        success = send_test_email(args.to)
        sys.exit(0 if success else 1)

    # Check Canvas API configuration
    if not canvas_api.is_api_configured():
        print("Error: Canvas API not configured")
        print("Set CANVAS_API_URL and CANVAS_API_KEY in .env file")
        sys.exit(1)

    # Get students
    students = canvas_api.get_students()
    if not students:
        print("No students found")
        sys.exit(1)

    print(f"Found {len(students)} student(s)")

    # Filter by student name if specified
    if args.student:
        students = [
            s for s in students
            if args.student.lower() in s.get("name", "").lower()
        ]
        if not students:
            print(f"No student found matching '{args.student}'")
            sys.exit(1)

    # Get recipients
    config = get_config()
    recipients = [args.to] if args.to else config.email.recipients

    if not recipients and not args.preview:
        print("Error: No email recipients configured")
        print("Set EMAIL_RECIPIENTS in .env or use --to flag")
        sys.exit(1)

    # Process each student
    include_chart = not args.no_chart
    success_count = 0

    for student in students:
        student_id = student["id"]
        student_name = student.get("name", "Unknown")

        print(f"\nProcessing: {student_name}")

        if args.preview:
            if preview_report(student_id, student_name, args.type, include_chart):
                success_count += 1
        else:
            if send_report(student_id, student_name, recipients, args.type, include_chart):
                success_count += 1

    # Summary
    print(f"\n{'=' * 50}")
    print(f"Completed: {success_count}/{len(students)} reports")

    sys.exit(0 if success_count == len(students) else 1)


if __name__ == "__main__":
    main()
